/**
 *
 *  @file agent_with_cache.cpp
 *  @author Gaspard Kirira
 *
 *  Copyright 2026, Gaspard Kirira.
 *  All rights reserved.
 *  https://github.com/vixcpp/vix
 *
 *  Use of this source code is governed by a MIT license
 *  that can be found in the License file.
 *
 *  Vix.cpp
 *
 */
#include <memory>
#include <string_view>

#include <vix/ai/agent/agent.hpp>
#include <vix/print.hpp>

namespace
{
  class CountingProvider final : public vix::ai::agent::ModelProvider
  {
  public:
    [[nodiscard]] std::string_view name() const noexcept override
    {
      return "counting";
    }

    [[nodiscard]] bool local() const noexcept override
    {
      return true;
    }

    [[nodiscard]] vix::ai::agent::AgentResult<bool> available() const override
    {
      return true;
    }

    [[nodiscard]] vix::ai::agent::AgentResult<vix::ai::agent::ModelResponse>
    generate(const vix::ai::agent::ModelRequest &request) override
    {
      ++calls_;

      vix::ai::agent::ModelResponse response;
      response.text = "This response was generated by the provider.";
      response.model = request.model;
      response.provider = "counting";
      response.status = vix::ai::agent::ModelResponseStatus::Completed;

      return response;
    }

    [[nodiscard]] int calls() const noexcept
    {
      return calls_;
    }

  private:
    int calls_{0};
  };
}

int main()
{
  vix::ai::agent::AgentConfig config;

  config.provider = "counting";
  config.model = "counting-model";

  config.allow_file_read = false;
  config.allow_process = false;
  config.allow_file_write = false;

  config.use_cache = true;
  config.cache_ttl_ms = 5 * 60 * 1000;
  config.persist_memory = true;

  auto provider = std::make_shared<CountingProvider>();

  vix::ai::agent::Agent agent(config, provider);

  vix::ai::agent::AgentRequest request;

  request.workspace = ".";
  request.input = "Explain local-first software in simple words.";
  request.mode = vix::ai::agent::AgentRequestMode::Explain;

  request.allow_tools = false;
  request.allow_file_read = false;
  request.allow_process = false;
  request.allow_file_write = false;
  request.use_cache = true;

  auto first = agent.run(request);

  if (!first)
  {
    vix::print("First run error:", first.error().message());
    return 1;
  }

  vix::print("First run:");
  vix::print(first.value().text);
  vix::print("From cache:", first.value().from_cache);
  vix::print("Provider calls:", provider->calls());
  vix::print();

  auto second = agent.run(request);

  if (!second)
  {
    vix::print("Second run error:", second.error().message());
    return 1;
  }

  vix::print("Second run:");
  vix::print(second.value().text);
  vix::print("From cache:", second.value().from_cache);
  vix::print("Provider calls:", provider->calls());

  return 0;
}
